### PR TITLE
View statistics function

### PR DESCRIPTION
**Pull request by junhui-phoon**

### CODE REVIEW

**Comment by junhui-phoon** [comment]
Calorie Stats:
image

Weight Stats:
image

Will change the miscellaneous stuff (background colour etc) later

**Review by wayne987 — COMMENTED** [review]
will it be better if theres another separate Statistic class that calculates all the required data for calorie and weight instead?

**Comment by junhui-phoon** [comment]
> will it be better if theres another separate Statistic class that calculates all the required data for calorie and weight instead?

no calculation involved here

**Comment by junhui-phoon** [comment]
Dark Theme for Charts:
image

**Comment by junhui-phoon** [comment]
Merge only after PR #103; need to verify sorting for charts

**Comment by junhui-phoon** [comment]
Changed to Bar Chart for calorie stats for better visualization:
image

**Review by ethanso56 — COMMENTED** [review]
looks good to me

**Pull request merged**
